[package]
name = "migrate_table"
version = "0.1.0"
authors = ["bpopadiuk <pboris@pdx.edu>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5"
migrate_table_derive = { path = "./migrate_table_derive" }
